name: "🚀 Feature request"
description: Suggest an idea for this project
title: '🚀'
labels: 'feature'
body:
  - type: textarea
    attributes:
      label: Type
      description: Describe if this a one-off feature or a series of features.
      placeholder: Describe the type of feature here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Description
      description: Describe if your feature request is related to a problem. Please describe the problem.
      placeholder: Describe the problem here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Solution Description
      description: Describe the solution you'd like, how it will impact you, and why we should implement it.
      placeholder: Describe the solution you'd like here...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Describe alternatives considered here...
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Provide additional context or screenshots here...
    validations:
      required: false
