apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: containers-package-{{repo_name}}
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      ( event == "pull_request" || ( event == "push" && source_branch == "main") ) && ( body.sender.login != "livewyer-bot" && body.sender.login != "lw-tkn[bot]" )

spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: containers-package

  params:
    - name: debug
      value: ""
    - name: url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: sourceBranch
      value: "{{source_branch}}"
    - name: targetBranch
      value: "{{target_branch}}"
    - name: subDirectories
      value: "containers"
    - name: fileName
      value: "Dockerfile"
    # -- Ref. <https://hub.docker.com/u/livewyer>
    - name: imageRegistry
      value: livewyer

  workspaces:
    - name: basic-auth
      secret:
        secretName: "{{git_auth_secret}}"
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
    - name: docker-config
      secret:
        secretName: lw-dockerhub-regcred

  taskRunTemplate:
    serviceAccountName: pipelines-as-code-runner
    podTemplate:
      securityContext:
        fsGroup: 65532
