apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: containers-package-containers
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      ( event == "pull_request" || ( event == "push" && source_branch == "main") ) && body.sender.login != "livewyer-bot"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: containers-package
  params:
    - name: url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: source_branch
      value: "{{ source_branch }}"
    - name: commit_sha
      value: "{{ revision }}"
    # -- Ref. <https://hub.docker.com/u/livewyer>
    - name: image_registry
      value: livewyer
  taskRunTemplate:
    serviceAccountName: pipelines-as-code-runner
    podTemplate:
      securityContext:
        fsGroup: 65532
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
    - name: dockerconfig
      secret:
        secretName: lw-dockerhub-regcred
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
