apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: public-containers-multi-build
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: |
      ( event == "pull_request" || ( event == "push" && source_branch == "main") ) && body.sender.login != "livewyer-bot"

    # The branch or tag we are targeting (i.e.: main, refs/tags/*)
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: containers-package-test
  params:
    - name: repo_owner
      value: "{{ repo_owner }}"
    - name: repo_name
      value: "{{ repo_name }}"
    - name: source_branch
      value: "{{ source_branch }}"
    - name: pull_request_number
      value: "{{ pull_request_number }}"
    - name: revision
      value: "{{ revision }}"
    # -- Ref. <https://hub.docker.com/u/livewyer>
    - name: image_registry
      value: livewyer
  taskRunTemplate:
    serviceAccountName: pipelines-as-code-runner
    podTemplate:
      securityContext:
        fsGroup: 65532
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 128Mi
    - name: dockerconfig
      secret:
        secretName: lw-dockerhub-regcred
